### ISSUE TITLE
wheres the addon folder in arch?

### ISSUE THREAD

**Issue by Janter1603** [JHGuitarFreak/UQM-MegaMod#254] opened 2024-10-18 05:08 UTC
I'm Trying to install precursor remix

**Comment by JHGuitarFreak** [comment] 2024-10-18 05:20
How'd you install it?

**Comment by JHGuitarFreak** [comment] 2024-10-18 05:23
I *believe* it's in the home folder under ./uqm-megamod
I've only ever worked in debian so you'll have to excuse my ignorance here.

If I were to check it'd probably be the same process any given Linux user would do is search for an addons folder on the hard drive and determine if its the megamods's or some other UQM installation's.

As I am more of a Windows developer than anything.

EDIT:

THAT BEING SAID... If you can access the binary via commandline you can make the addon directory any directory you want via the `--addondir` CLI. You don't necessarily have to deal with the default.

**Comment by JHGuitarFreak** [comment] 2024-10-19 00:06
Closing for now as it's not a bug.

**Closed as completed by JHGuitarFreak** 2024-10-19 00:06 UTC
